<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegio [
     <!ELEMENT colegio (alumnos, profes)> --es posen totes les etiquetes
     <!ELEMENT alumnos(alumno+)>
     <!ELEMENT alumno(nombre,apellido,matricula,activo|noactivo)>
     <!ATTLIST alumno expediente CDATA #REQUIRED>
     <!ELEMENT nombre (#PCDATA)>
     <!ELEMENT apellido (#PCDATA)>
     <!ELEMENT matricula (#PCDATA)>
     <!ELEMENT activo EMPTY>
     <!ELEMENT nactivo EMPTY>
     <!ELEMENT profes (profe+)>
     <!ELEMENT profe (nombre,curso,foto)>
     <!ELEMENT curso (#PCDATA)>
     <!ELEMENT foto (#CDATA)>
]>

<colegio>
<alumnos>
   <alumno expediente="AA01">
      <nombre>Marc</nombre>
      <apeliido>Venteo</apeliido>
      <matricula>ASIX</matricula>
      </activo>
   </alumno>
   <alumno expediente="AA02">
      <nombre>Ana</nombre>
      <apeliido>Venteo</apeliido>
      <matricula>DAW</matricula>
      </noactivo>
   </alumno>
</alumnos>

<profes>
   <profe>
   <nombre>Juan</nombre>
   <curso>DAW</curso>
   <foto>Juan.jpg</foto>
   </profe>
</profes>

</colegio>

